---
title: "Basic set &amp; number theory"
format: html
---

::: {.callout-note}
**Video:** [Basic set/number theory — 5:19](https://www.youtube.com/watch?v=9f-hGSh8lF0&t=319s)

This section corresponds to **5:19** in *Proof of Fermat Last Theorem FROM SCRATCH*.
:::

## 📌 Common number sets

We will use the following standard number systems:

👉 $\mathbb{N}$: the set of natural numbers

$$
\mathbb{N} = \{1, 2, 3,\cdots\}
$$

👉 $\mathbb{Z}$: the set of integers (the letter "Z" comes from the German word for numbers, namely "Zahle")

$$
\mathbb{Z} = \{\cdots, -2, -1, 0,1, 2, 3,\cdots\}
$$

👉 $\mathbb{Q}$: the set of rational numbers

$$
\mathbb{Q} = \{\frac{a}{b}\ \big|\ a, b \in \mathbb{Z}, b \neq 0\}
$$
👉 $\mathbb{R}$: the set of real numbers

👉 $\mathbb{C}$: the set of complex numbers

$$
\mathbb{C} = \{x +iy\ |\ x, y \in \mathbb{R}\}
$$

## 📌 Carthensian product

For sets $A$ and $B$, the Cartesian product is defined as

$$
A \times B := \{(a,b)\ |\ a \in A, b\in B \}
$$

Here, the multiplaction sign "$\times$" defines the way in which the new set is be formed from two other sets.

### 🏷️ Example 1 

Let $A=\{ 1, 2\}$ and $B=\{3, 4, 5\}$, then

$$
A \times B = \{(1,3), (1,4), (1,5), (2,3), (2,4), (2,5) \}
$$

### 🏷️ Example 2 

Let $A=\{ 1, 2\}$, then

$$
A \times A = A^2 = \{(1,1), (1,2), (2,1), (2,2) \}
$$

### 🏷️ Example 3: $\mathbb{R}^2$

$$
\mathbb{R}^2= \{(x,y)\ |\ x,y \in \mathbb{R}^2 \}
$$

## 📌 Symbols and abbreviations

- $\forall$: for all<br/>
- $\exists$: there exists<br/>
- $:=$: is defined as<br/>
- $w.l.o.g$: without loss of generality<br/>
- $s.t.$: such that<br/>
- $WTS$: want to show<br/>
- $ETS$: enough to show<br/>

## 📌 Divisibility and congruence

- $a|b$ means $a$ divides $b$, i.e., there exists $k$ such that $b=ak$.<br/>
- $a\nmid b$ means $a$ does not divide $b$.<br/>
- For integers $a, b$, and $n\geq 1$,

$$
a \equiv b\quad (\text{mod}\ {n})\quad \text{means}\ n\ |\ (a-b).
$$



### 🏷️ Examples 

$$
17 \equiv 32\quad (\text{mod}\ 5), 15 \equiv 29\quad (\text{mod}\ 7) 
$$

## 📌 Greatest common divisor

For integers $a,b$ the **greatest common divisor** of $a$ and $b$ is denoted by $\gcd(a,b)$, and is sometimes written as $(a,b)$.

- If $(a,c) = 1$, then $(ab,c)=(b,c)$
- For any integer $k$, $(a,b)=(a,b-ak)$
- If $(a,b) = 1$ and $a\ |\ bc$, then $a\ |\ c$

::: {.callout-note}
🚨 Why do we need this? 

The material below is used to proof Fermat's last theorem for the cases $n=3$ and $n=4$. Since these cases won't be included on this site, we will skip the proofs and details.
:::

### 🏷️ Examples 

- $\gcd(24, 36)=12$
- $\gcd(28, 49)=7$
- $\gcd(17, 32)=1$ (co-primes)
