---
title: "Basic calculus &amp; complex analysis"
format: html
---

::: {.callout-note}
**Video:** [Basic Calculus and Complex Analysis — 38:59](https://www.youtube.com/watch?v=9f-hGSh8lF0&t=2339s)

This section corresponds to **38:59** in *Proof of Fermat Last Theorem FROM SCRATCH*.
:::

## 📌 Taylor series {#taylor-series}

A Taylor series represents a function as an infinite polynomial. With infinitely many terms, it equals the original function within its interval of convergence.

#### 🏷️ **Examples**

$$
\begin{array}{rl}
e^x &= 1 + x + \dfrac{x^2}{2!} + \dfrac{x^3}{3!} + \cdots \\
\sin x &= x - \dfrac{x^3}{3!} + \dfrac{x^5}{5!} - \dfrac{x^7}{7!}+\cdots\\
\cos x &= 1 - \dfrac{x^2}{2!} + \dfrac{x^4}{4!}-\dfrac{x^6}{6!}+\cdots \\
\ln(1 + x) &= x - \dfrac{x^2}{2}+\dfrac{x^3}{3}-\dfrac{x^4}{4}+\cdots \qquad (-1 < x \leq 1)
\end{array}
$$

::: {.callout-note}
So why do we need this? 

Although this won't be used frequently in the forthccoming chapters, it appears a few times later.
:::

🎯 The Taylor series is a way to represent a given function as an infinite polynomial.

👉 We will look at the Taylor expansion again [from the perspective of linear algebra](/chapter-2/linear-algebra.qmd) in chapter two.

### 👨‍💻 Taylor expansion demo

```{=html}
<div id="taylorSeriesContainer"></div>
<script type="module" src="https://www.hendrikse.name/helion/examples/taylor_expansion.js"></script>
```

## 📌 Multivariable functions

A multivariable function is a map 

$$
f: \mathbb{R}^n \rightarrow \mathbb{R}
$$

In the section above, we have discussed (the Taylor expansion for) functions that depend on one variable only, such as $f(x) = e^x$. In this section, we'll shortly look at functions that depend on two or even more variables. 

A multivariable function that depends on two variables can naturally be visualized as a surface in three-dimensional space.

### 👨‍💻 Multivariable functions demo

```{=html}
<div id="realSurfacesContainer"></div>
<script type="module" src="https://www.hendrikse.name/helion/examples/real_surfaces.js"></script>
```

<p style="clear: all"></p>
Another examples may be choosen from the drop-down menu. The formula of the selected function can be seen in the title.

## 📌 Partial derivative

For functions that depend on more than one variable, we would like to be able to analyse the rate of change in a similar way to that of functions that depend on one variable only. As multivariate functions have several variables, each direction generally has its own rate of change. As a consequence, each direction has its own derivative. When looking for the rate of change in a particular direction, we leave the other variables intentionally unchanged. This means that all the other variables but the one we are interested in can then be treated as constants. 

Let $f:\mathbb{R}^2\rightarrow\mathbb{R}$ be a function. The partial derivative with respect to $x_i$ is defined as

$$
\dfrac{\partial f}{\partial x_i} :=
\lim_{h\rightarrow 0}
\dfrac{f(x_1,\cdots,x_i+h,\cdots,x_n) - f(x_1,\cdots,x_n)}{h}
$$

Note that this is very similar to the way in which the derivative is defined for a function of one variable:

$$
f'(x) =
\lim_{h\rightarrow 0}
\dfrac{f(x+h) - f(x)}{h}
$$

::: {.callout-note}
So why do we need this? 

Later these partial derivatives will show up when we talk about singlar points and elliptic curves.
:::

#### 🏷️ **Example**

Let

$$
f(x,y) = x^3+y^3+xy+\sin x\cos y
$$

then

$$
\begin{array}{ll}
\dfrac{\partial f}{\partial x} &=
3x^2 + y + \cos x\cos y \\
\dfrac{\partial f}{\partial y} &=
3y^2 + x - \sin x\sin y \\
\end{array}
$$


## 📌 Eurler's formula and $e^{i\theta}$

For any real number $\theta$,

$$
e^{i\theta} = \cos\theta + i\sin\theta.
$$

::: {.callout-note}
Why do we need this?

This formula tells us concretely what to do/what to think of, whenever we encounter $i$ in an exponent.
:::

The special case where $\theta = \pi$ then gives us one of the well-known formulas in mathematics, similar to the $E=mc^2$ equation in physics:

$$
e^{i\pi} + 1 = 0.
$$

The reason is that it contains so many important constants in one tiny equation:

- Euler's constant or natural constant $e$
- The irrational number $pi$ as the ratio between the circumverence and diameter of a circle
- The square root of negative one, $i$
- The identity with respect to addition, $0$
- The identity with respect to multiplication, $1$

This formula also matches very well with the aforementioned Taylor series.

$$
\begin{array}{ll}
e^x &= 1 + x + \dfrac{x^2}{2!} + \dfrac{x^3}{3!} + \cdots \\
e^{i\theta} &= 1 + i\theta - \dfrac{\theta^2}{2!} - \dfrac{\theta^3}{3!}i + \dfrac{\theta^4}{4!} + \dfrac{\theta^5}{5!}i - \dfrac{\theta^6}{6!} + \cdots \\
\quad &= \left(1 - \dfrac{\theta^2}{2!} + \dfrac{\theta^4}{4!} - \dfrac{\theta^6}{6!} + \cdots \right) +i\left(\theta - \dfrac{\theta^3}{3!}i + \dfrac{\theta^5}{5!} + \cdots\right) \\
\quad &= \cos\theta \qquad + \qquad i\sin\theta
\end{array} 
$$

As a consequence we have $e^{2\pi i} = 1$, $e^{\pi i} = -1$, and $e^{\frac{\pi}{6}i} = \dfrac{\sqrt{3}}{2} +\dfrac{1}{2}i$.

And more generally
$$
e^{i\theta} =
e^{i(\theta + 2n\pi)},\quad n\in\mathbb{N}.
$$

## 📌 The $n$-th roots of unity

::: {.callout-note}
🚨 So why do we need this? 

Roots of unity are used in many branches of mathematics, and are especially important in number theory, the theory of group characters, and the discrete [Fourier transform](/chapter-2/linear-algebra.html#example-2-fourier-transform). &mdash; [Wikipedia](https://en.wikipedia.org/wiki/Root_of_unity)
:::

The $n$-th roots of unity  are the complex numbers $z$ that satisfy the equation:

$$ 
z^n =1\quad \text{or equivalently}\quad z^n -1 = 0
$$

using Euler's formula, we can find all $n$ distinct roots. They are given by: 

$$
z_k=e^{i\dfrac{2\pi k}{n}}=\cos\left(\dfrac{2\pi k}{n}\right) + i\sin\left(\dfrac{2\pi k}{n}\right), \quad k=0, 1, 2,\cdots,n-1.
$$

So how does this work? We are looking for

$$
z^n = 1 = e^{2\pi k} \Rightarrow z = e^{\dfrac{2\pi ik}{n}},\quad k \in \mathbb{Z} 
$$

Filling in the values of $k$, we get

$$
\underbrace{
1, e^{\dfrac{2\pi i}{n}}, e^{\dfrac{4\pi i}{n}}, \cdots,e^{\dfrac{2\pi i(n-1)}{n}}
},
\underbrace{e^{2\pi i}, e^{\dfrac{2\pi i(n+1)}{n}}, \cdots
}
$$

Because of the periodicity, we can limit the values of $k$ to $n-1$.

#### 🏷️ **Example** 1: $n=2$

$$z_k = e^{i\dfrac{2\pi k}{2}} = e^{\pi ik} \Rightarrow \begin{cases} k=0: 1 \\ k=1: -1\end{cases}
$$

#### 🏷️ **Example** 2: $n=3$

$$z_k = e^{\dfrac{2\pi ik}{3}} \Rightarrow \begin{cases} k=0: 1 \\ k=1: e^{\dfrac{2\pi}{3}}= +\dfrac{\sqrt{3}}{2}i-\dfrac{1}{2} \\ k=2: e^{\dfrac{4\pi}{3}} = -\dfrac{\sqrt{3}}{2}i+\dfrac{1}{2}\end{cases}
$$

Geometrically, the roots of unity constitute the vertices of a regular $n$-gon sitting on a unit circle in the complex plane.

### 👨‍💻 Roots of unity demo

```{=html}
<div id="rootsOfUnityContainer"></div>
<script type="module" src="https://www.hendrikse.name/helion/examples/roots_of_unity.js"></script>
```

## 📌 Complex functions and holomorphy

A complex function is a map 
$$
f:\mathbb{C}\rightarrow\mathbb{C}
$$

$f$ is **complex differentiable** at $z_0$ if the limit below exists for $h\in\mathbb{C}$. 

$$
f'(z_0) := \lim_{h\rightarrow 0}\dfrac{f(z_0+h) - f(z)}{h}
$$

If $f$ is complex differentiable on an open set, it is called **holomorphic**.

### 👨‍💻 Complex functions

```{=html}
<div id="complexSurfacesContainer"></div>
<script type="module" src="https://www.hendrikse.name/helion/examples/complex_surfaces.js"></script>
```