---
title: "Abstract algebra"
format: html
---

::: {.callout-note}
This section corresponds to [Groups, Homomorphisms, and Group Actions — 2:44:50](https://www.youtube.com/watch?v=9f-hGSh8lF0&t=9890s) in the video *Proof of Fermat Last Theorem FROM SCRATCH*. [Noah Jang](https://www.linkedin.com/in/noah-jang-2111392ba/) is the original creator of the exposition and examples referenced here. The interactive implementations, animations, additional explanations, and contextual material are my own work.
:::

# Abstract algebra

::: {.callout-note}
🚨 Why do we need this? 

The main topics for proving Fermat's last theorem will be elliptic curves and modular forms. One of the most important facts about elliptic curves is the fact that their points form a group. It is the reason why we can view elliptic curves as algebraic objects.
:::

We start with groups, then we move on to rings and fields. These are the algebraic structrures we need before elliptic curves start making sense. 

At the end, we will also take a glimpse at Galois theory. This will become extremely important later, because Galois representations are one of the most important objects that establish a connection between elliptic curves and modular forms.



